### ISSUE TITLE
Implementing Django Gallery microservice with Nodejs Backend

### ISSUE THREAD

**Issue by SrikanthVelpuri** [airavata-courses/PingIntelligence#32]
[gallery-service.zip](https://github.com/airavata-courses/PingIntelligence/files/6133769/gallery-service.zip)
[https://github.com/airavata-courses/PingIntelligence/tree/contributor_srikanth/microservices/gallery-service](url)

**Comment by sudip-padhye** [comment]
@SrikanthVelpuri The above-mentioned link looks good, however since we already have our front-end ready along with our backend, I don't see any specific reason to incorporate that change. Moreover, the above project follows monolithic which would be difficult for us to disintegrate. 

If you have any more insights, please share.

**Comment by sudip-padhye** [comment]
@SrikanthVelpuri Also, could you please create a new issue for the 'Image tagging' microservice, which you are currently working on, and update the status there?

Thank You!

**Comment by sudip-padhye** [comment]
This issue is pending development & beyond the deadline. So closing this issue.
